---
rmqdefaults:
  - name: AMQP_EXCANGE
    value: xchg_integrations
  - name: AMQP_USER
    value: "{{ rmq.user }}"
  - name: AMQP_PASSWORD
    value: "{{ rmq.password }}"
  - name: AMQP_HOSTNAME
    value: rmq

registry_name: "localhost:5000/"

services:
  - name: api
    version: latest
  - name: app
    version: latest
  - name: converter
    version: latest
  - name: rmq
    version: latest

non_build_services:
  - name: rmq
    version: latest

git_repo: https://github.com/AlariCode/

configs:
  converter:
    queue: q_imageProcessor
