---
- name: "{{ name }} Configuration"
  ansible.builtin.include_tasks: "../secret.yml"

- name: "{{ name }} Service deploy"
  block:
    - name: "{{ name }} Service deploy"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "{{ registry_name }}{{ name }}:{{ version }}"
        state: present
        networks:
          - name: "{{ network_name }}"
        secrets:
          - secret_name: "{{ name }}.env"
            filename: "/opt/app/.env"
  tags: "{{ name }}"
