---
- name: Preconfig block (update system, install docker repos)
  block:
    - name: Update apt
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common
        state: present
    - name: Create docker GPG directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    - name: Add Docker's GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        update_cache: true
      tags: dockerrepo
- name: Install Docker
  block:
    - name: Installing docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - python3-pip
        state: present
        update_cache: true
- name: Install pip3 docker
  block:
    - name: Install pip3 docker
      ansible.builtin.pip:
        name: docker
        state: present
- name: Add user & group
  block:
    - name: Create group
      ansible.builtin.group:
        name: docker
        state: present
    - name: Create user and append to group
      ansible.builtin.user:
        name: vagrant
        groups: docker
        append: true
    - name: Enable and start docker
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started
    - name: Enable and start contair
      ansible.builtin.systemd:
        name: containerd
        enabled: true
        state: started
